@baseUrl = http://127.0.0.1:5050

# Create a new user
POST {{baseUrl}}/api/account/register
Content-Type: application/x-www-form-urlencoded

username=QcTrung
&email=quoctrung@gmail.com
&password=12345
&cfmPassword=12345
