services:
    server1:
        image: node:latest
        container_name: server1
        working_dir: /app
        volumes:
            - ./server:/app
        command: bash -c "npm i && npm start"
        ports:
            - "5000:5000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
    
    server2:
        image: node:latest
        container_name: server2
        working_dir: /app
        volumes:
            - ./server:/app
        command: bash -c "npm i && npm start"
        ports:
            - "5001:5000"
        depends_on:
            - redis
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
    
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6378:6379"
        volumes:
            - ./redis-data:/data

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            server1:
                condition: service_healthy
            server2:
                condition: service_healthy

volumes:
    app:
        